name: Test Access to Azure

on:
    workflow_call:
        secrets:
            AZURE_CLIENT_ID:
                required: true
            AZURE_TENANT_ID:
                required: true
            AZURE_SUBSCRIPTION_ID:
                required: true

permissions:
    id-token: write # Required for OIDC
    contents: read
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}

jobs:
  test-access:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2.3.0
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI Action
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az resource list
